### PR TITLE
fix: fix typo in `Lines` docstring

### PR DESCRIPTION
**Pull request by joshiayush**
fix typo in `Lines` docstring 

Signed-off-by: Ayush Joshi <ayush854032@gmail.com>

### CODE REVIEW

**Review by Conchylicultor — CHANGES_REQUESTED** [review]
I'm not sure I understand the point of this function. Aren't those features already tested in `test_lines_nested_indent` ?

There is a maintenance cost of having too many tests, which is why we try to keep tests as simple and minimal as possible in general.

**Comment by joshiayush** [comment]
```python
  assert text == epy.dedent("""
      [
        a,
        b,
        [
          c,
          d,  # I was curious to see if this context will repeat itself after exiting
        ],
      ]
      """)
```

```python
def test_lines_with_nested_object_indent():
  ...
    with lines.indent():
      for submodule in submodules:
        for k, v in submodule.items():
          lines += '{'
          with lines.indent():  # next iteration will test if this context will produce expected result or not
            lines += f'\'{k}\': \'{v}\','
          lines += '},'
    lines += '],'
  ...
  text = lines.join()

  assert text == epy.dedent("""
        ...
        submodules: [
          {
            'epath': 'Path utils',  # I was curious to see if this context will repeat itself after exiting
          },
          {
            'epy': 'Python utils',  # it repeats itself
          },
          {
            'ejax': 'Jax utils',  # it repeats itself
          },
        ],
        ...
        """)
```

@Conchylicultor You are the Google engineer here :), I might not make any sense but this is how I learnt testing 😂. Should I update the PR to only fix the typo?

**Comment by Conchylicultor** [comment]
> @Conchylicultor You are the Google engineer here :), I might not make any sense but this is how I learnt testing 😂. Should I update the PR to only fix the typo?

Yes, thank you for fixing the typo. Let's revert the test and only submit that.

**Comment by joshiayush** [comment]
@Conchylicultor Done.

**Pull request merged**
